name: '@actalog/download-docker-volumes'
description: 'Download docker volumes'
author: Gabriel Rufino <contato@gabrielrufino.com>
branding:
  icon: download
  color: blue

inputs:
  host:
    description: 'SSH server host'
    required: true
  username:
    description: 'SSH username'
    required: true
  password:
    description: 'SSH password'
    required: true
  port:
    description: 'SSH port'
    required: false
    default: '22'
  volumes-path:
    description: 'Docker volumes directory path'
    required: false
    default: '/var/lib/docker/volumes'
  artifact-retention-days:
    description: 'Number of days to retain the artifact (only applicable when upload-mode is `artifact`)'
    required: false
    default: '7'
  backup-password:
    description: 'Password to protect the backup file'
    required: true
  upload-mode:
    description: 'Upload mode: "artifact" to upload as GitHub artifact, "local" to save on the runner'
    required: false
    default: 'artifact'
  local-path:
    description: 'Local path to save the backup file when upload-mode is "local"'
    required: false
    default: '/tmp/docker-volumes-backup.zip'

outputs:
  backup-path:
    description: 'Backup file path: in "artifact" mode, the local filename ("docker-volumes-backup.zip"); in "local" mode, the full local path.'
    value: ${{ steps.backup.outputs.backup-path }}

runs:
  using: composite
  steps:
    - id: backup
      shell: bash
      run: |
        set -e

        echo "::add-mask::${{ inputs.password }}"
        echo "::add-mask::${{ inputs.username }}"
        echo "::add-mask::${{ inputs.host }}"
        echo "::add-mask::${{ inputs.port }}"
        echo "::add-mask::${{ inputs.backup-password }}"

        # Define variables
        VOLUMES_DIR="docker-volumes"
        if [ "${{ inputs.upload-mode }}" = "local" ]; then
          BACKUP_FILE="${{ inputs.local-path }}"
        else
          BACKUP_FILE="docker-volumes-backup.zip"
        fi
        PASSWORD="${{ inputs.backup-password }}"

        # Download the volumes directory using rsync
        sshpass -p "${{ inputs.password }}" \
          rsync \
            -avzP \
            -e "ssh -p ${{ inputs.port }} -o StrictHostKeyChecking=no" \
            ${{ inputs.username }}@${{ inputs.host }}:"${{ inputs.volumes-path }}/" "$VOLUMES_DIR/"

        # Compress and add password
        zip -P "$PASSWORD" -r "$BACKUP_FILE" "$VOLUMES_DIR"
        rm -rf "$VOLUMES_DIR"

        # Set output
        echo "backup-path=$BACKUP_FILE" >> $GITHUB_OUTPUT
    - if: ${{ inputs.upload-mode == 'artifact' }}
      uses: actions/upload-artifact@v4
      with:
        name: docker-volumes-backup
        path: ${{ steps.backup.outputs.backup-path }}
        retention-days: ${{ inputs.artifact-retention-days }}
    - if: always()
      shell: bash
      run: |
        rm -f ~/.ssh/known_hosts
        echo "SSH known_hosts cleaned"
