name: '@actalog/download-docker-volumes'
description: 'Download docker volumes'
author: Gabriel Rufino <contato@gabrielrufino.com>
branding:
  icon: download
  color: blue

inputs:
  host:
    description: 'SSH server host'
    required: true
  username:
    description: 'SSH username'
    required: true
  password:
    description: 'SSH password'
    required: true
  port:
    description: 'SSH port'
    required: false
    default: '22'

runs:
  using: composite
  steps:
    - uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        port: ${{ inputs.port }}
        script: |
          set -e
          tar -czf "/tmp/docker-volumes-$(date +%Y%m%d_%H%M%S).tar.gz" -C "/var/lib/docker/volumes" .
          ls -t /tmp/docker-volumes-*.tar.gz | head -1 > /tmp/backup-path.txt
          echo "Backup created: $(cat /tmp/backup-path.txt)"
    - shell: bash
      run: |
        set -e
        sudo apt-get update -qq && sudo apt-get install -y sshpass
        
        BACKUP_FILE=$(sshpass -p "${{ inputs.password }}" ssh -p ${{ inputs.port }} -o StrictHostKeyChecking=no \
          ${{ inputs.username }}@${{ inputs.host }} "cat /tmp/backup-path.txt")
        
        sshpass -p "${{ inputs.password }}" scp -P ${{ inputs.port }} -o StrictHostKeyChecking=no \
          ${{ inputs.username }}@${{ inputs.host }}:"$BACKUP_FILE" ./
        
        echo "Downloaded: $(basename $BACKUP_FILE)"
    - uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        port: ${{ inputs.port }}
        script: |
          rm -f /tmp/docker-volumes-*.tar.gz /tmp/backup-path.txt
          echo "Cleanup completed"
