name: '@actalog/download-docker-volumes'
description: 'Download docker volumes'
author: Gabriel Rufino <contato@gabrielrufino.com>
branding:
  icon: download
  color: blue

inputs:
  host:
    description: 'SSH server host'
    required: true
  username:
    description: 'SSH username'
    required: true
  password:
    description: 'SSH password'
    required: true
  port:
    description: 'SSH port'
    required: false
    default: '22'
  volumes-path:
    description: 'Docker volumes directory path'
    required: false
    default: '/var/lib/docker/volumes'
  artifact-retention-days:
    description: 'Number of days to retain the artifact'
    required: false
    default: '7'
  backup-password:
    description: 'Password to protect the backup file'
    required: true

runs:
  using: composite
  steps:
    - uses: appleboy/ssh-action@v1.2.4
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        port: ${{ inputs.port }}
        timeout: 60s
        script: |
          set -euo pipefail

          VOLUMES_PATH="${{ inputs.volumes-path }}"
          if [ ! -d "$VOLUMES_PATH" ]; then
            echo "Error: Directory $VOLUMES_PATH not found"
            exit 1
          fi

          PASSWORD="${{ inputs.backup-password }}"

          BACKUP_FILE="/tmp/docker-volumes-backup.zip"
          zip -P "$PASSWORD" "$BACKUP_FILE" -r "$VOLUMES_PATH"
          echo "Backup created with password protection: $BACKUP_FILE"
    - shell: bash
      run: |
        set -e
        sudo apt-get update -q && sudo apt-get install -y sshpass zip

        # Define variables
        VOLUMES_DIR="docker-volumes"
        BACKUP_FILE="docker-volumes-backup.zip"
        PASSWORD="${{ inputs.backup-password }}"

        sshpass -p "${{ inputs.password }}" scp -r -P ${{ inputs.port }} -o StrictHostKeyChecking=no \
          ${{ inputs.username }}@${{ inputs.host }}:"${{ inputs.volumes-path }}" "$VOLUMES_DIR"

        zip -P "$PASSWORD" -r "$BACKUP_FILE" "$VOLUMES_DIR"
        echo "Backup created: $BACKUP_FILE"

        rm -rf "$VOLUMES_DIR"
    - uses: actions/upload-artifact@v4
      with:
        name: docker-volumes-backup
        path: docker-volumes-backup.zip
        retention-days: ${{ inputs.artifact-retention-days }}
    - if: always()
      shell: bash
      run: |
        rm -f ~/.ssh/known_hosts
        echo "SSH known_hosts cleaned"
