FROM docker:dind

RUN apk add --no-cache \
    openssh \
    openssh-server \
    bash

RUN ssh-keygen -A && \
    mkdir -p /run/sshd && \
    echo "root:testpassword" | chpasswd && \
    sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

RUN mkdir -p /var/lib/docker/volumes/test-volume/_data && \
    echo "test data" > /var/lib/docker/volumes/test-volume/_data/test.txt

EXPOSE 22

RUN printf '#!/bin/sh\n\
dockerd-entrypoint.sh &\n\
sleep 5\n\
/usr/sbin/sshd -D\n' > /start.sh && \
    chmod +x /start.sh

CMD ["/start.sh"]
