FROM docker:dind

RUN apk add --no-cache \
    openssh \
    openssh-server

RUN ssh-keygen -A && \
    mkdir -p /run/sshd && \
    echo "root:testpassword" | chpasswd && \
    sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

EXPOSE 22

RUN mkdir -p /var/lib/docker/volumes/test-volume/_data && \
    echo "test data" > /var/lib/docker/volumes/test-volume/_data/test.txt

COPY entrypoint.test.sh /entrypoint.test.sh
RUN chmod +x /entrypoint.test.sh

ENTRYPOINT ["/entrypoint.test.sh"]